name: CI/CD Pipeline for Python Web Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  linting:
    name: Static Code Analysis
    runs-on: ubuntu-latest

